### ISSUE TITLE
What does `shard` do?

### ISSUE THREAD

**Issue by NanoCode012** [winglian/axolotl#14]
In latest update, there is `shard` argument. What is it trying to do? Is it trying to load model then output lora adapter? 

https://github.com/winglian/axolotl/blob/cb9a88704707b0fc3362988a7f57b606e4448ac7/scripts/finetune.py#L169-L171

Is this due to how you're saving full model now?

https://github.com/winglian/axolotl/blob/cb9a88704707b0fc3362988a7f57b606e4448ac7/scripts/finetune.py#L222

As I understand, if you want to extract lora from checkpoint, you need to load from the checkpoints first, then set the base model with those weights. If this `shard` meant something different, could I PR this feature of lora extraction from checkpoint?

**Comment by winglian** [comment]
this is mostly a helper that will take a `pytorch_model.bin` and shard it into files of ~10GB. Useful when you have a checkpoint that you want to share.

**Comment by NanoCode012** [comment]
Cool! Thanks for the clarification
